apiVersion: v1
kind: Namespace
metadata:
  name: trivyk8swebhook

---

apiVersion: v1
kind: Secret
metadata:
  name: trivyk8swebhook-certs
  namespace: trivyk8swebhook
type: Opaque
data:
  trivy-k8s-webhook.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQyekNDQWNNQ0NRRGNWZ1R0S1RnVmN6QU5CZ2txaGtpRzl3MEJBUXNGQURBVk1STXdFUVlEVlFRRERBcEIKUTJ4dmRXUkhkWEoxTUNBWERUSXhNRFV4TkRJd01ERXlPVm9ZRHpJeE1qRXdOREl3TWpBd01USTVXakJJTVFzdwpDUVlEVlFRR0V3SlZVekVMTUFrR0ExVUVDQXdDVkZneEREQUtCZ05WQkFvTUEwRkRSekVlTUJ3R0ExVUVBd3dWCllXTm5MblJ5YVhaNUxtczRjeTUzWldKb2IyOXJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUF0b2JUVlM1U1pRaEVnZ21oNWtNa2JGaStDMlBqWnZMQ0NhektQU3ZUK1hiQ3luQk5vam56NTNuTwozRHBJWWhJV3RJY2xyVlpqMVVpWDF4WHZwU0xCNlNXT3lETnJTWnZDbjhwQk94VWlXYzRGYXc3czgvYm5SMFNDClN3MzJ0cUJZVWNWc1h5L3lrdXE1VEVCdVpLUDlPZ0FyMkZRSVVQZm5yMVFOalYzWThQOERROEl5K2xUbUU5NHQKdkZQa1dRUzUrNjRuSFYxSmhISEFYcjFSLzhZUCtjSVIxSXgyY2Q0Y2NVeW10clhiV2crYlN3YmZqOXBpRC9OYQovWEtZSVJvWEZQUmI4QjRINFZpL2hxNlowTXZmdXl0dTU3dWUvWmlwS3plLzk5c0hpVmRFNERWYy80MjhlVVhqCjlEaVBZbFN1aUtIcHl5N1IwUkY5M0RsbFVVSHhvd0lEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQjcKTzdUakhFbzRZQ1Z0NUlyZllFNWpsVE8xOEpXbEtkSndaOXg1TDRiV0xnNm4za3hsVkZ6anVRRjN6M0FvdEFvbwpsVWdaK211aGl6SzRTMWhYVEJIZlhrRVhnRXVyaC8xSXNINFYrR2NqVTQxaWtxY1AvaHQ1YS84eThYOHYrYUFECmNqOVJKK2M2QXhjQURCSHc0SHlvcVJOUkhzc01oYmFXY3plNGFXT3NUTXg5NkFUT3Rma3Q1RUZwcC81eXdtQm4KYjZoTGJqb2hQTjdjWFkydmpKZVoxeGZnSzFaRjRsYW54UVJMbUNhWmQ2dnVMTG1vZCs5cGhRM1pRZHprcXZCUwpCei9HV2pEdEFuSmtvWHIyUjZodUlVQ1lhUzNEVm9IK3pjbWpqTUMyVXhDUWxEaXBiOFM5TVAyRkJTSDZGejZhCjl4N3A1emplamlnemtlQ1lESzFJbmp1SVI3RXIzMVUzclc0VlMrTHAyV2gwT3ZnblRaQVRLVmRGSWZPUnVlVWsKNWNVS2dicTVoS2lxVHYzekNPdTFhTmN1emxKTW1KeTFxRjV0djUzRnZqRk1qUEliY3BPRy9EQ1JSNDZBUzFQZwpRSlZOME5jNkY2VXptN3pobVVvMDJTckp2U1lxQVJ3bHpYelV1UEk4blVpWmxZclRqUGJlRmNiblpEZ1RhQkd3CngwNFJvdEFjVzZKUWY3YjdIcHliRlc2M1c5TFdUZDA5TVJiRVZ2dDNXQkU4U3U1OXE5bkQ5c28zSm9VOWpoNTgKT1VOS2MrN0lMTzhlOXUrU2lEWCt0cXlMYThRNDlHWU1wNlM1MzBYRmVtaWtzNXpGQXJNdjIvVHRDbGtDWUVCaQpRSzJOd1hjQnRKM0w1am1xTFFQTUpkdGJnbHhzcEF0WS8rSEVrcjBMTWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  trivy-k8s-webhook.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdG9iVFZTNVNaUWhFZ2dtaDVrTWtiRmkrQzJQalp2TENDYXpLUFN2VCtYYkN5bkJOCm9qbno1M25PM0RwSVloSVd0SWNsclZaajFVaVgxeFh2cFNMQjZTV095RE5yU1p2Q244cEJPeFVpV2M0RmF3N3MKOC9iblIwU0NTdzMydHFCWVVjVnNYeS95a3VxNVRFQnVaS1A5T2dBcjJGUUlVUGZucjFRTmpWM1k4UDhEUThJeQorbFRtRTk0dHZGUGtXUVM1KzY0bkhWMUpoSEhBWHIxUi84WVArY0lSMUl4MmNkNGNjVXltdHJYYldnK2JTd2JmCmo5cGlEL05hL1hLWUlSb1hGUFJiOEI0SDRWaS9ocTZaME12ZnV5dHU1N3VlL1ppcEt6ZS85OXNIaVZkRTREVmMKLzQyOGVVWGo5RGlQWWxTdWlLSHB5eTdSMFJGOTNEbGxVVUh4b3dJREFRQUJBb0lCQUJpRHJ5cUhtQ1Zkb09YZQpLVkpsdmlTWEhwOGxBVXU0V3ZzMXE4dmZjUTdXTm44OTZnOVp2VHBmajdyZ1VReHE1WVhGaVBmbzNHdXUza1hTCittYXhibDNEMzVOZjVJNzBUb1ZyZ3F0T3dWaFNaVVBsczBsbzVkTWFqbTFLS05LS1lwSkk4Njh0SDJWQUJUY0sKaUVrWUJWQ2U2VVNhdEtzN1FIQzUxMEFmVkoyNVNBdnpDd3g1WFN4bFJBM0MyRjJBa1J4YnhhQkduc2dsNXQ5agpVaE5pdjlmTGh3ekx1RExNcUdLV3Y2MUdJQzQ5QXVSdHVmd2YrL1NxR1VHWEZ3dmN1SFpzUThNakRlQWx3QVk3Clp6K2VzRkEzemFwOXFYYm5nd0J6ck9SMmFnVmxUWFhxc1VYaWxSVWVyRzM4WHB1RkY3bUZzYWl5b0xXaUNZNCsKNG5hdE12RUNnWUVBNjlQWU1jcjdjZlVReXowaGROSFh5bm5pM2duanZJMGZaZDVJYVAxNjBtakhMTTBuOE5MYgpwNGk2YmdtbFJYczlVSzZOcWpDZVdCMmwyNGFKTTJud096SnRmaHllTUlJSjdDdGZBYmFpTzZhT0xndm1QZDNjCmdHZGdVQnlvRjlJN09kU1VPZU51cWtraHlkN1kxalM1cGJPRng4TVlZb0NWMTNNTTN6d0VZYlVDZ1lFQXhpUE0KUUY2K3JWMSt5VEZYWG5sNmtxU2NoTEtQQ3RJUzY0bG90ZHUwUWRyZld6ZlRJVFVBWXVYcnJVMnNqU0p2MWxrMgphejJPU1hLZS9wSnFWYTRuZHUzWk9sVG1tSVBvSnkyYlp5Y1Q4aXl4VXl4YndBbmt0SnAyeDZEdkorbGpDc2I4CmJWL1ZkYW8rZHlKU2dIZUw3c0ZLazBaQzgzZENmbkRXNFFOa2ZQY0NnWUVBaTJ4Umt3Nm9uZlQvR3NsbmNFTm4KeXVOSXgzRWRYU29wOS9YMDVXMkhJY0tranM0ejRPTW96ZUcrSnJRNUs5enlvVEt4dW43SC90eDRaRk1qNW11cApoYllJbWRpZGhadzc5WTZtdXNLWkk1OFN6QkpvNndheUNKQVZsd2Q2TWFzdkxMK0xhcllWaFVON1lIZ0p4b3FoCmYxK2xwamFud2dTM2tnc0kveW5paFVrQ2dZQUE4TFNNYmFhci9mQ1hGZFBiVCtwRC9lSDhRemlvalh5bmYzeHUKdUg4dmZORm9obWhMRlF4T2E5YmxlS1BqKzVEYVRJd1VrRE0zcUFLWEpLeTZnVndRbFdwZGUzK29vNStiWi96Lwp6VkNyNm9oZzQ2bi96RXc0aXk4YkhXbGxJQmRuT3JDQitGMXo5SDNkWk4xTlhNUGVPeTZXYWxQeEFkVGY4cnNpClVEak8yd0tCZ1FEcDlkc1dlSG5tUEg4cGVob1hzYzR4a0RoWEh0SUVGZldEV3hET0JYU0ZJTEtFWjVHY2NyWXIKZW16RjNObkY4b05mbnNybWIzQmlnZGh6bGtrenNNYjVlbFcwdlFMd2dwK3cvS1B3WHZrMkN5a2l5cTVyUHJraQpIQy9EN3lGNkR1QndMcFk0dWdValNLaHJHajFIaFhRcnZOaWNDM2g1VlBTS3JnMEQrdXJQZXc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivyk8swebhook
  namespace: trivyk8swebhook
  labels:
    contact: WillB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivyk8swebhook
  template:
    metadata:
      labels:
        app: trivyk8swebhook
    spec:
      containers:
      - name: nginx
        image: linuxacademycontent/trivy-k8s-webhook:0.0.1
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: trivyk8swebhook-certs

---

apiVersion: v1
kind: Service
metadata:
  name: trivyhook
  namespace: trivyk8swebhook
spec:
  selector:
    app: trivyk8swebhook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
