apiVersion: v1
kind: Namespace
metadata:
  name: trivyk8swebhook

---

apiVersion: v1
kind: Secret
metadata:
  name: trivyk8swebhook-certs
  namespace: trivyk8swebhook
type: Opaque
data:
  trivy-k8s-webhook.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVUakNDQWphZ0F3SUJBZ0lKQU9ycExDQnpHU2wvTUEwR0NTcUdTSWIzRFFFQkN3VUFNQjh4RERBS0JnTlYKQkFzTUEwRkRSekVQTUEwR0ExVUVBd3dHUTB0VElFTkJNQ0FYRFRJeE1EVXhOVEF5TURNME5Wb1lEekl4TWpFdwpOREl4TURJd016UTFXakFnTVI0d0hBWURWUVFEREJWaFkyY3VkSEpwZG5rdWF6aHpMbmRsWW1odmIyc3dnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzFsZC93T0NmeTJ6Q2lnVkxHaU5wQnlPejkKQW9NSDdubzVjS21EVGJuS0VhQ2lzUXhqRFQzRlJ6NVcxcXQ0ZThFQW42YWJFZ3p5NHNlN1lZVjJNUTM2SGQzSwp3bThuU1JsRUY3M0htQzMvZDFpOXBES0NYY1FPeTJ3ZVBhYks3U2d2RHBHTWVIL1RFOXF0NUpobnpvWi9UR2FmCk0zTWZ3Vy9GNTY1SHRNeFhGZXUxT2RvT1dKQTVZN1M1cER6Qyt6ajJHS2ZFSUR6dlgydklyZFJRSlFsMFVJME0KY2k4SlpXZWVQVGlHUEhhZGpKNndKSCs5eE5TK2F0aUZwWHBNZVFmV3F2cEd6R0ZjQU5TaUJhTzRneGRSbVpMSwpTRnB5a2JOdVpYZ0NIc3Yxb2E1WjJCWEhrbmpCbnUwSGpEUmtlZDhkL3dPRVpqaWZxKzRkVWxSZ3dnckZBZ01CCkFBR2pnWWt3Z1lZd0RnWURWUjBQQVFIL0JBUURBZ1dnTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwbEJCWXcKRkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01FY0dBMVVkRVFSQU1ENkNLM1J5YVhaNWFHOXZheTUwY21sMgplV3M0YzNkbFltaHZiMnN1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDQ1d4dlkyRnNhRzl6ZEljRWZ3QUFBVEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUZzeEFBaW1RZkFGVk0rbUpycGxPTUVMbUl0Ni96aEZqMDQ2NDUvbkkKN1UzdkpMSml2cTFzZ1lTWEZ5UURmSUdLa3hIUitQOWVKMUFmMUlGTkdwMldIc3V3OVE0VTRQaVlxdXNYaE5mSgpJT3VVTnBlc3FQTHVpb3c4Y2N6MFFsNC9rU2l1Q0liMGM5YnFpU21haHNSWDFzMm5nY25HR21Ya2syM3B0TTZ6Cjd2cHJqUmZqUm0vZTdpZ2YxeEpKWGQ5Slp0NGZXWUhDQm83eHBLNjk1a3p0a0JXd0RXd1FZd0t2SXBra0RSMy8KdnZiWkZSOGI4SGVQSkJKKzJqMVNLTXRHZUJSU0pFeXE4UEg1VEs4NFNUZ0hNSi9tTlZpdndVamFEbTVyempzWQo1ajA0QlA0cWNxQlcvLzZDV3psWkY4UDlBKzRRZ0diVmxKY1EwR3R3YmErcGtTZU90R2ZBL0FWL0o1OE5NUTJ5ClNrNjBndTRtMk5sRTdvSlg1bksrcnpWTkE1aEFFM094ZFdGUk9oNHQvZStoWS9qVGx1UVFobGNsTG1lY3RwMEYKSzRtbG56UHZBUnQ2Njg2YmIxMkZoR0RaVkZjSUN3NVpEQlpjaEVOdmp0OVpINDZuNGl1VTdORVhaWnU0T0taYgp4NzVzTTEwMXRFUFNpQUlkU3Z0MUJmM2JTY0gzNHFSQTh6MGxKemNEWmpuejRBRzl0QnVuOHY3VlltRS9jNUZiCjRGYi9zQk85ZlcvbWVBSmt4LzZvSlF2VjlVSHlWcGtEYW9JOFd3dHE1d24xdmN4VkViT1F2M2xDUkhvaElHNlMKQW1RV2hHdmNxZWw0M0xrakhvS2plblA5U2lHaXpKQkhYV2ZJdUgrN1Q2cEZwWXJxZ0xMdHpjUm4zTVM1QW5tQwprL2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  trivy-k8s-webhook.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdFpYZjhEZ244dHN3b29GU3hvamFRY2pzL1FLREIrNTZPWENwZzAyNXloR2dvckVNCll3MDl4VWMrVnRhcmVIdkJBSittbXhJTTh1TEh1MkdGZGpFTitoM2R5c0p2SjBrWlJCZTl4NWd0LzNkWXZhUXkKZ2wzRURzdHNIajJteXUwb0x3NlJqSGgvMHhQYXJlU1laODZHZjB4bW56TnpIOEZ2eGVldVI3VE1WeFhydFRuYQpEbGlRT1dPMHVhUTh3dnM0OWhpbnhDQTg3MTlyeUszVVVDVUpkRkNOREhJdkNXVm5uajA0aGp4Mm5ZeWVzQ1IvCnZjVFV2bXJZaGFWNlRIa0gxcXI2UnN4aFhBRFVvZ1dqdUlNWFVabVN5a2hhY3BHemJtVjRBaDdMOWFHdVdkZ1YKeDVKNHdaN3RCNHcwWkhuZkhmOERoR1k0bjZ2dUhWSlVZTUlLeFFJREFRQUJBb0lCQVFDVUoxOVo0SWQvbHlUYwpRY1dtcEh2bkZxZDlXdkpMbzJCbnd5c2JMV3g3bU54R1FVd0krUUhBRnZ1ZTRIRncwUS9Na1hYZXFlQ1V2MEVVCittRm82R2N0L2ZZNisxNnpYK25VYThaMHRnNDVsRWQ4R3g3MnpNZ3RCZjRGd21sMndmNTZQbG0wa1pCQlNMNncKQ0lYc2xFMmFTVnlsWWRYNVA5c1JUcEVjZ2tBQ2dFZEdOdldQUzZYZFpFSFJrUE9QZ0xTZFM5MUxWZXdlYjZuUgp0d0tvRy96cSs3U29wMDI0Z3hPdWI3bnZ3UEZYaExieG1UZVZhZWlqVVVVNE5mcmozckI0MitqYWpnSVkrcEhPCittZDhJUVRxWWF0NnlNYWJmN21ESU4vaXhZQ1R6TmVldDNZOWFLZ3Y3a3lJQ3ZvL0ZXVVBCQW9aSU92c2liQVkKWUdLRi9SdjFBb0dCQU8vamtmdStUWFFJV0xicnNSeEN5Y1ZQQXc1SmJvSjcxNWN5cVJBRFRWODhMbDF2eFdyZgpTUm1yWW5jMkc0Kzhud0JjR3R1YWhabUkrVjBnL25hUXlTQ3lFRU81R1NYRDdoUlQ1R1J6dXNuN1F0eWFId3VECkJKZDlTK0pIeUJHT3EzSlVSaFZYREVhMit4Yk16ZUVCaXVKd1B3bk1Kd0E5d3VMbjZXMmhTREkvQW9HQkFNSEgKNDBpOFpxNjl1UENYYVBXMDVpZnRNVHNnMVg2ZmlpVjdJYzFVUHU4cFZQclRtQll1dG1PWFU4UUtKeVkzaUJXeApPQUQ2QTNLZjZCRy9LK0ErT3A1UGpXM0R5RENoWWN2U1Z1NzhxTExiZDBOMXJuWGFhWVNNTlViS2V4a2lRZGJCCmM0dzRYR0hVT0tpUmJreUZTOUdYdnRTbktpQXFGQ1lQN001Z2gzbjdBb0dBVUFlejVEQ1ExbTBTYTdRbDJpL04KOEsxemI0aS8vWGdqYktYU0VTMkkyb1RSVXdxKzZmQ2tDcFJLdlVxbjEwUXVKNGlTelVDMzRZajQ2RURobzl5Wgp2UGFxeG0weUhvOUhGakVHdVJ5QzdHK08xdG4wRVhzY1JRM2dDeFczZ1dQL2ZwenU1Sit0ME1tcTZ1aFlwd0JFCnZWYUZNVmVTaTFvUGNuTzhSSDdSL3pFQ2dZRUFrbWFhNzNQdk8rdDRVc1NCZHNpeDdjNUVtSUJvNjU1Szk2QTgKWEcxZWtyK3VSVVloSy9ra3NMOCtlT2lXeFVmRkYyWnBna3RnMlhPNEY5aFBwTDQrK1NYdkd0T0Vaa0UycW8rQwpRRkpBZmNoVEpYTStXQ21uK0kwWkh4K1F1dDluMElFYzgvNE14WmhaS2ZtZDFGQU1oUS9aQzc0emxGTldINTkrCmNEajdnWXNDZ1lFQTN0TnpteUo5QTN3QkF5czlsZ29GWEk4RElhVVR0UDF0UE02eWNjdnJNcy9vdmlFeStMY1EKMUF2UHU4NDRnOHovNENvdmw1V0tJeGFYcXQxYVdLVm91TTB1TjdtaGFHSHFlaWFSOXJqTWxuSTZBYVJwTVRjMwpFYjRsNkRlaUNsdVJhZzhhRkY3aDN0NWRsWFhTQkt5dVZSbTFBQ0ZObUt2dTNTd3o0aWQvdWJ3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivyk8swebhook
  namespace: trivyk8swebhook
  labels:
    contact: WillB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivyk8swebhook
  template:
    metadata:
      labels:
        app: trivyk8swebhook
    spec:
      containers:
      - name: nginx
        image: linuxacademycontent/trivy-k8s-webhook:0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
        ports:
        - containerPort: 8090
      volumes:
      - name: certs
        secret:
          secretName: trivyk8swebhook-certs

---

apiVersion: v1
kind: Service
metadata:
  name: trivyhook
  namespace: trivyk8swebhook
spec:
  type: NodePort
  selector:
    app: trivyk8swebhook
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30099
