apiVersion: v1
kind: Namespace
metadata:
  name: trivyk8swebhook

---

apiVersion: v1
kind: Secret
metadata:
  name: trivyk8swebhook-certs
  namespace: trivyk8swebhook
type: Opaque
data:
  trivy-k8s-webhook.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVUakNDQWphZ0F3SUJBZ0lKQUtYcEJxMnBIYjNGTUEwR0NTcUdTSWIzRFFFQkN3VUFNQjh4RERBS0JnTlYKQkFzTUEwRkRSekVQTUEwR0ExVUVBd3dHUTB0VElFTkJNQ0FYRFRJeE1EVXhOREl3TlRZME1Gb1lEekl4TWpFdwpOREl3TWpBMU5qUXdXakFnTVI0d0hBWURWUVFEREJWaFkyY3VkSEpwZG5rdWF6aHpMbmRsWW1odmIyc3dnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ1o0MjVkc3RFOGltZ1NRdk1yaVczd2VlS00KaEYrYWJKeHNaTC9JSlBXRlc2Vm5veGZ6anlTYkFkMEFvYzZNWmpNdWxNejVESHhzcTVqZGNHbEFndnpGNzl1YQpnRi9aZkJxOGtrTVVpcVdFS3Q5YmQyRXF1YTRYZjZNcUZ2dVozZG9NMmd5ZWhlYXk5bVBxT1Z6M1NLN1hCZTZuCk5hNW9PNVJaWXY3d2NpZnBvV2RCOStOaVorMXVGWDRod2FOdlpsVE5Xb3BXTTJHRUFCY3UrNzhnZU16U3RjdGkKTUVBWmJEUENoWUJtK0FEeFJpVXR3RXEyVVNWeVZvVTM1eXE2NGhTYlUxOTNWOGE0T3dMeGZqV29DbTJjOC9YeQp1THhUUHN3ZEtiQ1VmWHdsMHFtdXE0UG1qTWhTV3NOMVNlUWZuWlNNYk1Mejg0U0RWKzYrMmx2Vm5RM0xBZ01CCkFBR2pnWWt3Z1lZd0RnWURWUjBQQVFIL0JBUURBZ1dnTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwbEJCWXcKRkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01FY0dBMVVkRVFSQU1ENkNLM1J5YVhaNWFHOXZheTUwY21sMgplV3M0YzNkbFltaHZiMnN1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDQ1d4dlkyRnNhRzl6ZEljRWZ3QUFBVEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQVZwVTNlcFFBZlRjYkFDc3VMNkgzbUhZTmpiQ2FLWFA3NWlDcVJnVnkKTTR1bkVSTjFQZ0F2cmZzaG42MlRXR0dMRDZUdHN2YnBwQ0YvSGVaL0ZWa3BHWndQUGxjMUVQV0lBN2t2eXhYbApCRzNQN1Aralczb0c4QThxOFhOM05hRlpOL3FMeHJ3SDVzR2dqT3JTYjdlaWdJaGNoQWlLZGhvUWQ1K0lkK0F3Ckp5MTRxU21wbXRjclNkNVZiQzh3RHg1NjdHVkpRZk1HbFo2NU5GcEFWaEQyUVQzNytnaDZKVWttS3cwRm9UV00KekFxOVpqK1RMdDJTRkRYUWR5c2NnaFpLRGZ3ZkV5TEx2L3ZUb0gwTUxZYmJQbHBscnA4MXlpcnRYSlJsQ2ZROQpaR3pVQ0RSL3hCVzcwRklNam1aK1pOV1pheGdNMlVTQzA3eXRoU1pwZXI3Y3dURkFWcGkzbWM0dzE1RmVFblZTCkNRdGpyK1BSdm1nQktUMU1hblBhUytySktXSkxrWkhJU1A5QmNxTVZvZUVLS082VXp4U1FnRzV5YmVQTVZjWkoKUWdkVXRFTWQxVUxHM1VDcWNEK0lvN3RqS2ZzZDg0bGxzMGtFS1JEUmZLSzY2Sm1OYnExRGxNcXp5c01Ha1ZoSQoxTi8xMVVrUTBlUWlnVk9BK1MvbjByVDBrQXNoT0ZsTzV5SGlrbGl2NUJZTmJUV2dYdG5zcnArR1c0bmd0YlAwCk8wVVM4Y2RoOG1Fc0QxdDFqWXk5bnBQbmx3STBDWlBNRldWMWUrY01IWEFmZkxBdTVvb2FrelpyT3VUdzYzWWIKQjFyRnUwaGZicmw0aVdkNE5HWDJybEpUR2NqTzBUb2N3RVRPWHZ6Q1ExeEowQVVPV055OHV3SUdYMlNYV2pudApjd0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  trivy-k8s-webhook.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbWVOdVhiTFJQSXBvRWtMeks0bHQ4SG5paklSZm1teWNiR1MveUNUMWhWdWxaNk1YCjg0OGttd0hkQUtIT2pHWXpMcFRNK1F4OGJLdVkzWEJwUUlMOHhlL2Jtb0JmMlh3YXZKSkRGSXFsaENyZlczZGgKS3JtdUYzK2pLaGI3bWQzYUROb01ub1htc3ZaajZqbGM5MGl1MXdYdXB6V3VhRHVVV1dMKzhISW42YUZuUWZmagpZbWZ0YmhWK0ljR2piMlpVelZxS1ZqTmhoQUFYTHZ1L0lIak0wclhMWWpCQUdXd3p3b1dBWnZnQThVWWxMY0JLCnRsRWxjbGFGTitjcXV1SVVtMU5mZDFmR3VEc0M4WDQxcUFwdG5QUDE4cmk4VXo3TUhTbXdsSDE4SmRLcHJxdUQKNW96SVVsckRkVW5rSDUyVWpHekM4L09FZzFmdXZ0cGIxWjBOeXdJREFRQUJBb0lCQUF5VGxiVjZvN2I2Nkw1MQpVa0pBblFlR0xvbWxWOXJhL1gydVRpNGhOeCtLK2QyYWFwNnhHQ0RDNmpqZkFHNWcrOVhXdTFtdk40djZDaWd1Cnc2dE9DVEowQTlLQW8xUzIyOGlGZTQzMk5zaXlhRWFsWHYrSzVUdHVadnRObllwWm96UmhyWjVXK3grdEcwVk4KSXRmaXpNY3Q2TzhwWi9PRXl2N3pKRHFxV2JDeUs3VmIrL3cyMVNMYkNqajZtSityaDNBKzNXQmRDT2xtNG1TUQozVllOS2N3aTNDM3ZYdmIvU0pjcW5wOFdldTRNUmR1bVR1YVdzU0tZZUpLY202N04ybjlrbWRLT3VMK1lXZE9yCkF5OEpManRVZHM4VXc2YWcybTJPcVJ0aGlmMGljMzBqYmhtc3RHYldVZTc5TTZJQkhrY0ZDRERQbDZmeFF1ZDQKV2lnYjVxRUNnWUVBekY3Y2w5Sm5jUHNOWGEzZG5KMVlDUitUNkpTakd6dEt1RWtsVTJxTnRubzk1bGhzWDdXdwpVTFhDN3M4RnRxdm44RkVSQ25NRlEwdGtSYnRYcUJWVHZqL1VTNFFBUzVzZmhQR3p2aUl2QmVWcHNpRXpINWpoCnJJaEs0cDFWaWE4dWNHa2R2aTFqRUZXUUQxSUxuanNOQTJlT2FhTDZ0NzF6WkN3R3M0UjUwQ1VDZ1lFQXdNUEUKUFppcGJtbDJ4ZFExeHp6c0haMElVcVF5Vnk3b2JYUk94eVpvZzNPVjVXSHNqbks2ODEvMjNsNkpuVGlZdHQrTApZSWZiU1lYandldVZoTWNocmo1Nm4xM09uN1lCTzBZYmxkTGpYOXFXK09VTEh5V1lpRHl1VG9sNnFuTDg1NmQrClVwTmRibWIyUWUrcCtqaDF5WW1vUjlTRTZ3QzhFSStjdFh5aFN5OENnWUVBbWNGOHdSUmhFcFV1ZHg1SnJueUsKTVVMNnFtNjVUOUdKNDUvVVh5KzVNbUpCazcxT3U2c2IzWDBDRFZ6ZmRaRmJ6R2VSSklWb25qcG9WRFlnT3FyZworQzlaYnY3K29lTXhFWG91dW90SlNXeFIydHd6ZEVBMitQRUpOZmtjMDV0aW10dmFycXZDN2hVUmJ4VlEvRmg4CjcrVEhOaDZSOWc2b2MrTFRuOWU1TmFrQ2dZRUFrbStsa28xNG1QSHhVcFBGVHRmUEh5ZjkvSm5UekR0TVFtb0sKdG10TkZoOG1qaHozMGJjQ29vUVNUQmRSUDJpUlNzdERYRStZbkovang1c3ArTFkxdGVLczBJZzR3VWRJWkRqOApGN01mRytBNHRGZDdQV3dZRmRiVEs4Snd0eStuUkd3UElMZm1VRXBUWlArbUJ2b0JNTnNzUlhVQ2pHd0FjaXhICkJlL3ByKzBDZ1lBZHlQL3NCbDRjaWdydkRmM3Z0V0dEYmorb0xhY1BmdFZhUVltMW1lWGtmZFFIbVBsL0RYVVAKQmlZaVBJOVdaQUN1c01BK2dRbmdJdUpnS0NIM3VJRTdMV05nUmNINlN3YWozZEFqcGw0WXZaNU9OVTR4OWloRwpKWGtxc1FWbGprSXhDd3dKSmFJM2g3UXhmb0tGSGR2UmFBcnp4eEZJMnJ1TmdHOWJmc2JqZVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivyk8swebhook
  namespace: trivyk8swebhook
  labels:
    contact: WillB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivyk8swebhook
  template:
    metadata:
      labels:
        app: trivyk8swebhook
    spec:
      containers:
      - name: nginx
        image: linuxacademycontent/trivy-k8s-webhook:0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: trivyk8swebhook-certs

---

apiVersion: v1
kind: Service
metadata:
  name: trivyhook
  namespace: trivyk8swebhook
spec:
  selector:
    app: trivyk8swebhook
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
